#!/bin/bash

# This script starts a number of other scripts (26 by default).
# To start eternal nalog.ru recovery requests cycle, run like this:
# bash ./starter -e ./nalog-recover -t 2 -l ./nalog.log

while getopts f:t:p:l:e:s: flag
do
    case "${flag}" in
        t) pMaxtime=${OPTARG};;
        l) pLog=${OPTARG};;
        e) pExec=${OPTARG};;
    esac
done


maxtime="$pMaxtime"
export maxtime

for x in {a..z}
do


log="$pLog.log"
export log


#echo "$maxtime"
#echo "$filename"
#echo "$proxylist"
#echo "$log"


exec "$pExec" &

sleep 0.5

done
